import{i as m,S as p}from"./assets/vendor-0fc460d7.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const h=document.querySelector(".loader");function l(o,e,s){m.show({iconUrl:o,titleColor:"White",titleSize:"24px",message:e,messageColor:"White",messageSize:"16px",backgroundColor:s,position:"topRight",timeout:3e3})}function g(){h.classList.remove("visually-hidden")}function b(){h.classList.add("visually-hidden")}function L(o){o.innerHTML=""}function f(o){return o.map(e=>`<li class="gallery-item">
    <a href="${e.largeImageURL}" data-lightbox="gallery-link">
      <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
    </a>
    <div class="gallery-info">
      <p><b>Likes:</b> ${e.likes}</p>
      <p><b>Views:</b> ${e.views}</p>
      <p><b>Comments:</b> ${e.comments}</p>
      <p><b>Downloads:</b> ${e.downloads}</p>
    </div></li>
  `).join("")}function y(o,e){const s="43325485-b0026802577d8a210f4fcd054",t=`https://pixabay.com/api/?${new URLSearchParams({key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15})}`;return fetch(t).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()})}const c="/goit-js-hw-12/assets/bi_x-octagon-06de2d57.svg",w=document.querySelector(".form"),d=document.querySelector(".gallery"),u=document.querySelector(".btn-load-more"),v=new p(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",captionPosition:"bottom"});w.addEventListener("submit",P);u.addEventListener("click",q);let n=1,S=null;function P(o){o.preventDefault();const e=o.currentTarget.search.value.trim();g(),u.classList.add("visually-hidden"),L(d),n=1,y(e,n).then(s=>{if(s.hits.total>0&&l(c,"Sorry, there are no images matching your search query. Please try again!","#ef4040"),s.hits.length===0)return l(c,"Sorry,   there are no images matching your search query. Please try again!","#ef4040");const i=f(s.hits);d.innerHTML=i,v.refresh()}).catch(s=>{console.error("Error:",s)}).finally(()=>{b()})}function q(){n+=1,y(S,n).then(o=>{list.insertAdjacentHTML("beforeend",f(o.hits));const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),Math.ceil(o.hits.total/15)===n&&(u.classList.add("visually-hidden"),l(c,"Sorry, there are no images matching your search query. Please try again!","#ef4040"))})}
//# sourceMappingURL=commonHelpers.js.map
